// Generated by CoffeeScript 1.7.1
(function() {
  var Dispatcher, Master, exports;

  Master = require('./master');

  Dispatcher = (function() {
    function Dispatcher() {
      return new Master;
    }

    return Dispatcher;

  })();

  exports = module.exports = Dispatcher;

}).call(this);
